apiVersion: v1
kind: Service
metadata:
  name: account-service
spec:
  selector:
    app: account-service
  ports:
  - port: 8080
    targetPort: 8080
  type: {{ .Values.service.type }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: account-service
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: account-service
  template:
    metadata:
      labels:
        app: account-service
    spec:
      containers:
        - name: account-service
          image: {{.Values.accountService.image.repository }}:{{ .Values.accountService.image.tag }}
          ports:
            - containerPort: {{ .Values.accountService.service.port }}
          env:
            - name: DB_USERNAME
              value: {{ .Values.postgresql.postgresqlUsername }}
            - name: DB_PASSWORD
              value: {{ .Values.postgresql.postgresqlPassword }}
          resources:
            requests:
              memory: {{.Values.accountService.resources.requests.memory }}
              cpu: {{.Values.accountService.resources.requests.cpu }}
            limits:
              memory: {{.Values.accountService.resources.limits.memory }}
              cpu: {{.Values.accountService.resources.limits.cpu }}


