apiVersion: v1
kind: Service
metadata:
  name: ledger-service
spec:
  selector:
    app: ledger-service
  ports:
    - port: {{ .Values.ledgerService.service.port }}
      targetPort: {{ .Values.ledgerService.service.port }}
  type: {{ .Values.service.type }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ledger-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ledger-service
  template:
    metadata:
      labels:
        app: ledger-service
    spec:
      containers:
        - name: ledger-service
          image: {{ .Values.ledgerService.image.repository }}:{{ .Values.ledgerService.image.tag }}
          ports:
            - containerPort: {{ .Values.ledgerService.service.port }}
          env:
            - name: DB_USERNAME
              value: {{ .Values.postgresql.postgresqlUsername }}
            - name: DB_PASSWORD
              value: {{ .Values.postgresql.postgresqlPassword }}
          resources:
            requests:
              memory: {{ .Values.ledgerService.resources.requests.memory }}
              cpu: {{ .Values.ledgerService.resources.requests.cpu }}
            limits:
              memory: {{ .Values.ledgerService.resources.limits.memory }}
              cpu: {{ .Values.ledgerService.resources.limits.cpu }}
