apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresql-pvc
spec:
  resources:
    requests:
      storage: {{ .Values.postgresql.postgresqlPvc.storage }}
  accessModes:
    - ReadWriteOnce

---
apiVersion: v1
kind: Service
metadata:
  name: postgresql
spec:
  ports:
    - port: {{ .Values.postgresql.servicePort }}
      targetPort: {{ .Values.postgresql.servicePort }}
  selector:
    app: postgresql
  type: {{ .Values.service.type }}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql
spec:
  selector:
    matchLabels:
      app: postgresql
  replicas: {{ .Values.postgresql.deployment.spec.replicas }}
  template:
    metadata:
      labels:
        app: postgresql
        tier: db
    spec:
      containers:
        - name: postgresql
          image: {{.Values.postgresql.image.repository}}:{{.Values.postgresql.image.tag}}
          ports:
            - containerPort: {{ .Values.postgresql.servicePort }}
          env:
            - name: POSTGRES_USER
              value: {{ .Values.postgresql.postgresqlUsername }}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.postgresql.postgresqlPassword }}
          resources:
            requests:
              memory: {{ .Values.postgresql.resources.requests.memory }}
              cpu: {{ .Values.postgresql.resources.requests.cpu }}
            limits:
              memory: {{ .Values.postgresql.resources.limits.memory }}
              cpu: {{ .Values.postgresql.resources.limits.cpu }}
          volumeMounts:
            - mountPath: {{ .Values.postgresql.volumeMounts.mountPath }}
              name: {{ .Values.postgresql.volumeMounts.name }}
      volumes:
        - name: {{ .Values.postgresql.volumeMounts.name }}
          persistentVolumeClaim:
            claimName: postgresql-pvc
          
# kubectl port-forward svc/postgresql 5432:5432