apiVersion: v1
kind: Service
metadata:
  name: ledger-service
spec:
  selector:
    app: ledger-service
  ports:
    - port: 8081
      targetPort: 8081
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ledger-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ledger-service
  template:
    metadata:
      labels:
        app: ledger-service
    spec:
      containers:
        - name: ledger-service
          image: jayesh888/ledger-service:9.0.0
          ports:
            - containerPort: 8081
          env:
            - name: DB_USERNAME
              value: postgres
            - name: DB_PASSWORD
              value: postgres
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
